spring.application.name=rtc
debug=false
spring.datasource.url=jdbc:postgresql://localhost:5433/rtcUsers
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.address=0.0.0.0
server.port=8080

spring.web.error.whitelabel.enabled=false
